# Generated by Django 4.1 on 2022-08-07 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_author_film_alter_genre_name_filminstance_film_genre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='isbn',
        ),
        migrations.AddField(
            model_name='film',
            name='year',
            field=models.CharField(default='Null', help_text='Year of the film', max_length=4, verbose_name='year'),
        ),
        migrations.AlterField(
            model_name='film',
            name='summary',
            field=models.TextField(help_text='Argumento breve de la película', max_length=1000, verbose_name='Summary'),
        ),
    ]
